name: Convert and Merge IPTV Lists

# on: 
#  workflow_dispatch:

on:
  schedule:
    - cron: '45 6 * * *'  # This action runs every day at midnight.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script
      run: |
        python .github/workflows/iptv.py

    - name: Commit and push if it changed
      run: |
        git diff
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Action"
        git commit -am "Update IPTV lists" || exit 0
        git push
