name: Update Google List

on:

  schedule:

    - cron:  '30 13 * * *'

jobs:

  update:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code

      uses: actions/checkout@v2

    - name: Set up Python

      uses: actions/setup-python@v2

      with:

        python-version: 3.8

    - name: Install dependencies

      run: |

        python -m pip install --upgrade pip

        pip install requests

      

    - name: Update Google List

      run: |

        python -c "

        import requests

        urls = [

            'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Surge/Google/Google.list',

            'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Twitter/Twitter.list',

            'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Tiktok/Tiktok.list',

        ]

        new_lines = []

        for url in urls:

            resp = requests.get(url)

            lines = resp.text.split('\n')

            new_lines.extend([line.replace('DOMAIN-SUFFIX,', '') for line in lines if line.startswith('DOMAIN-SUFFIX,')])

        with open('Google.txt', 'w') as f:

            f.write('\n'.join(new_lines))

        "

    - name: Commit and push if it changed

      run: |

        git diff

        git config --local user.email "action@github.com"

        git config --local user.name "GitHub Action"

        git add .

        git commit -m "Update Google List" || exit 0

        git push
